[package]
name = "playing-with-nannou"
version = "0.1.0"
authors = ["Taylor Arnett <tarnett1@mac.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.14.1"